# Generated by Django 2.1.4 on 2019-03-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190324_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
